service: omni-p44-location-updates

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: true
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  timeout: 30
  memorySize: 256
  deploymentBucket: ${ssm:/omni-dw/${self:provider.stage}/sls/deployment/bucket}
  role: ${ssm:/omni-dw/${self:provider.stage}/lambda/role}
  stackTags:
    Application: P44LocationUpdates
    CreateBy: BizCloudExperts
    Version: "1.0"
    Environment: ${self:provider.stage}
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    SERVICE: ${self:service}

plugins:
  - serverless-offline

functions:
  locationUpdatesApi: ${file(config/functions/locationUpdates.yml):function}

custom:
  standardResponseHeaders:
    "Access-Control-Allow-Origin": "'*'"
    "Access-Control-Allow-Credentials": "'true'"
    "Access-Control-Allow-Headers": "'*'"

package:
  individually: true

layers:
  CommonLibs:
    path: lib
    name: ${self:service}-layer-${self:provider.stage}
    description: p44-location-updates-layer-${self:provider.stage}
    compatibleRuntimes:
      - nodejs14.x
    retain: false

resources:
  Resources:
    BadRequestResponse:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: ACCESS_DENIED
        ResponseTemplates:
          application/json: |
            {
              "errorDescription":"$context.authorizer.message"
            }
        RestApiId:
          Ref: "ApiGatewayRestApi"
        StatusCode: "400"
    AuthFailureGatewayResponse:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: "ApiGatewayRestApi"
        StatusCode: "401"
    LocationUpdatesP44DLQ: ${file(config/queues/locationUpdatesP44Queue.yml):LocationUpdatesP44DLQ}
    LocationUpdatesP44Queue: ${file(config/queues/locationUpdatesP44Queue.yml):LocationUpdatesP44Queue}
