function:
  name: omni-p44-process-from-sqs-${self:provider.stage}
  handler: src/p44ProcessFromSQS/index.handler
  description: P44 Process From SQS - ${self:provider.stage}
  runtime: nodejs14.x
  events:
    - sqs:
        arn: arn:aws:sqs:us-east-1:332281781429:omni-p44-location-updates-queue-${self:provider.stage}
        batchSize: 10
        maximumBatchingWindow: 60
        functionResponseType: ReportBatchItemFailures
  environment:
    P44_LOCATION_UPDATE_TABLE: ${ssm:/omni-p44/location-updates/${self:provider.stage}/source/ddb.table_name}
    P44_SQS_QUEUE_URL: ${ssm:/omni-p44/location-updates/${self:provider.stage}/source/SQS.queue_url}
