---
function:
  name: omni-p44-process-from-sqs-${self:provider.stage}
  handler: src/p44ProcessFromSQS/index.handler
  description: P44 Process From SQS - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  layers:
    - { Ref: CommonLibsLambdaLayer }
  package:
    include:
      - "src/p44ProcessFromSQS/index.js"
      - "src/shared/**"
    exclude:
      - "**/*"
  events:
    - sqs:
        arn: arn:aws:sqs:us-east-1:332281781429:omni-p44-location-updates-queue-${self:provider.stage}
        batchSize: 10
        maximumBatchingWindow: 60
        functionResponseType: ReportBatchItemFailures
