function:
  name: omni-p44-process-dynamo-streams-${self:provider.stage}
  handler: src/p44ProcessDynamoStreams/index.handler
  description: P44 Process From DynamoDB Streams - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  # layers:
  #   - { Ref: CommonLibsLambdaLayer }
  # package:
  #   include:
  #     - "src/p44ProcessDynamoStreams/index.js"
  #     - "src/shared/**"
  #   exclude:
  #     - "**/*"
  events:
    - stream:
        type: dynamodb
        arn: ${ssm:/omni-p44/location-updates/${self:provider.stage}/source/ddb.stream_arn}
        filterPatterns:
          - eventName: [INSERT]
  environment:
    SHIPMENT_HEADER_TABLE: ${ssm:/omni-wt-rt-updates/${self:provider.stage}/shipment-header/ddb.tableName~true}
    CUSTOMER_MCKESSON: ${ssm:/omni-p44-rt-updates/${self:provider.stage}/mckesson-customer/numbers}
    TABLE_NAME: ${ssm:/omni-p44/location-updates/${self:provider.stage}/stepFunction-status/ddb.table_name}
    TABLE_ARN: ${ssm:/omni-p44/location-updates/${self:provider.stage}/stepFunction-status/ddb.table_arn}
    STREAM_ARN: ${ssm:/omni-p44/location-updates/${self:provider.stage}/stepFunction-status/ddb.stream_arn}
    TABLE_INDEX_KEY: ${ssm:/omni-p44/location-updates/${self:provider.stage}/stepFunction-status/ddb.stepFunctionStatus_index}
