---
function:
  name: omni-p44-process-from-sqs-${self:provider.stage}
  handler: src/p44ProcessFromSQS/index.handler
  description: P44 Process From SQS - ${self:provider.stage}
  runtime: nodejs14.x
  layers:
    - { Ref: CommonLibsLambdaLayer }
  package:
    include:
      - "src/p44ProcessFromSQS/index.js"
      - "src/shared/**"
    exclude:
      - "**/*"
  logSubscription: true
  events:
    - sqs:
        arn:
          Fn::GetAtt:
            - LocationUpdatesP44Queue
            - Arn 
        batchSize: 10
        maximumBatchingWindow: 60
        functionResponseType: ReportBatchItemFailures
  environment:
    FUNCTION_NAME: omni-p44-process-from-sqs-${self:provider.stage}
    SERVICE_NAME: ${self:service}
    APPLICATION: DataWarehouse
    SNS_TOPIC_ARN: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
	  REGION: ${self:provider.region}
