---
function:
  name: omni-p44-process-dynamo-streams-${self:provider.stage}
  handler: src/p44ProcessDynamoStreams/index.handler
  description: P44 Process From DynamoDB Streams - ${self:provider.stage}
  runtime: nodejs14.x
  layers:
    - { Ref: CommonLibsLambdaLayer }
  package:
    include:
      - "src/p44ProcessDynamoStreams/index.js"
      - "src/shared/**"
    exclude:
      - "**/*"
  logSubscription: true
  events:
    - stream:
        type: dynamodb
        arn: ${ssm:/omni-p44/location-updates/${self:provider.stage}/source/ddb.stream_arn}
        filterPatterns:
          - eventName: [INSERT]
  environment:
    SHIPMENT_HEADER_TABLE: ${ssm:/omni-wt-rt-updates/prod/shipment-header/ddb.tableName~true}
    P44_SF_STATUS_TABLE: ${ssm:/omni-p44/location-updates/${self:provider.stage}/stepFunction-status/ddb.table_name}
    LOCATION_UPDATE_SHIPMENT_STATUS_INDEX: ${ssm:/omni-p44/location-updates/${self:provider.stage}/stepFunction-status/ddb.stepFunctionStatus_index}
    CUSTOMER_MCKESSON: ${ssm:/omni-p44-rt-updates/${self:provider.stage}/mckesson-customer/numbers}
    FUNCTION_NAME: omni-p44-process-dynamo-streams-${self:provider.stage}
    SERVICE_NAME: ${self:service}
    APPLICATION: DataWarehouse
