---
function:
  name: omni-p44-process-ddb-sf-status-${self:provider.stage}
  handler: src/p44ProcessSfStatus/index.handler
  description: P44 Process From SF DynamoDB Streams - ${self:provider.stage}
  runtime: nodejs14.x
  layers:
    - { Ref: CommonLibsLambdaLayer }
  package:
    include:
      - src/p44ProcessSfStatus/index.js
      - src/shared/helper.js
      - src/shared/joiSchema.js
      - src/shared/dynamoDb.js
      - src/shared/logger.js
    exclude:
      - "**/*"
  events:
    - stream:
        type: dynamodb
        arn: arn:aws:dynamodb:us-east-1:332281781429:table/omni-p44-location-sf-status-${self:provider.stage}/stream/2023-05-08T15:17:39.813
        filterPatterns:
          - eventName: [INSERT]
  logSubscription: true
  environment:
    STEP_FUNCTION_ARN: ${ssm:/omni-p44/location-updates/${self:provider.stage}/source/state_machine_arn}
