---
function:
  name: omni-p44-send-events-${self:provider.stage}
  handler: src/p44SendEvents/index.handler
  description: P44 send events to endpoint - ${self:provider.stage}
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  layers:
    - { Ref: CommonLibsLambdaLayer }
  package:
    include:
      - "src/p44SendEvents/index.js"
      - "src/shared/**"
    exclude:
      - "**/*"
  environment:
    SF_TABLE_INDEX_KEY: ${ssm:/omni-p44/location-updates/${self:provider.stage}/stepFunction-status/ddb.stepFunctionStatus_index}
    P44_API_URL: ${ssm:/omni-p44/location-updates/${self:provider.stage}/source/API.url}
