---
function:
  name: omni-p44-send-events-${self:provider.stage}
  handler: src/p44SendEvents/index.handler
  description: part of omni-p44-process-location-updates-${self:provider.stage} sf that sends events to p44 API
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  layers:
    - { Ref: CommonLibsLambdaLayer }
  package:
    include:
      - "src/p44SendEvents/index.js"
      - "src/shared/**"
    exclude:
      - "**/*"
  logSubscription: true
  environment:
    SHIPMENT_HEADER_TABLE: ${ssm:/omni-wt-rt-updates/prod/shipment-header/ddb.tableName~true}
    REFERENCE_TABLE: ${ssm:/omni-wt-rt-updates/prod/references/ddb.tableName~true}
    SF_TABLE_INDEX_KEY: ${ssm:/omni-p44/location-updates/${self:provider.stage}/stepFunction-status/ddb.stepFunctionStatus_index}
    P44_API_URL: ${ssm:/omni-p44/location-updates/${self:provider.stage}/source/API.url}
    FUNCTION_NAME: omni-p44-send-events-${self:provider.stage}
    SERVICE_NAME: ${self:service}
    APPLICATION: DataWarehouse
