---
function:
  name: omni-p44-update-hwb-status-${self:provider.stage}
  handler: src/p44UpdatesHwbStatus/index.handler
  description: part of omni-p44-process-location-updates-${self:provider.stage} sf that updates hawbs to pending, keeping ready to process for p44 API
  runtime: nodejs14.x
  memorySize: 2048
  timeout: 900
  layers:
    - { Ref: CommonLibsLambdaLayer }
  package:
    include:
      - "src/p44UpdatesHwbStatus/index.js"
      - "src/shared/**"
    exclude:
      - "**/*"
  logSubscription: true
  environment:
    P44_SF_STATUS_TABLE: ${ssm:/omni-p44/location-updates/${self:provider.stage}/stepFunction-status/ddb.table_name}
    SF_TABLE_INDEX_KEY: ${ssm:/omni-p44/location-updates/${self:provider.stage}/stepFunction-status/ddb.stepFunctionStatus_index}
    P44_LOCATION_UPDATE_TABLE_INDEX: ${ssm:/omni-p44/location-updates/${self:provider.stage}/source/ddb.shipmentStatus_index}
    FUNCTION_NAME: omni-p44-update-hwb-status-${self:provider.stage}
    SERVICE_NAME: ${self:service}
    APPLICATION: DataWarehouse
    SNS_TOPIC_ARN: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
    REGION: ${self:provider.region}