function:
  name: omni-location-updates-api-${self:provider.stage}
  handler: src/locationUpdatesApi/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }
  package:
    include:
      - src/locationUpdatesApi/**
      - src/shared/**
    exclude:
      - "**/*"
  events:
    - http:
        path: /updates
        method: POST
        private: true
