---
stateMachine:
  name: omni-p44-process-location-updates-${self:provider.stage}
  definition:
    Comment: "Step function to process location updates"
    StartAt: PublishEvents
    States:
      PublishEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:omni-p44-update-hwb-status-${self:provider.stage}"
        Next: SendEvents
      SendEvents:
        Type: Task
        Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:omni-p44-send-events-${self:provider.stage}"
        End: true
      SuccessState:
        Type: Succeed
