---
stateMachine:
  name: omni-p44-process-location-updates-${self:provider.stage}
  definition:
    Comment: "Step function to process location updates"
    StartAt: SendEvents
    States:
      SendEvents:
        Type: Task
        Resource: "arn:aws:lambda:us-east-1:332281781429:function:omni-p44-send-events-dev"
        End: "true"
